// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eiwdlivdhoiwzmfxzvzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpd2RsaXZkaG9pd3ptZnh6dnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc4OTY2NjIsImV4cCI6MjA4MzQ3MjY2Mn0.Xb9zh3GXBaKwJfb_9dSG86LMwkHBmopFb0QKzNBAaRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);